apiVersion: apps/v1

kind: Deployment

metadata:

  name: attendance-backend

spec:

  replicas: 1

  selector:

    matchLabels:

      app: attendance-backend

  template:

    metadata:

      labels:

        app: attendance-backend

    spec:

      containers:

        - name: backend

          image: utkarsh2101/attendance-system:latest

          ports:

            - containerPort: 8080

          env:

            - name: SPRING_DATASOURCE_URL

              value: jdbc:mysql://attendance-mysql-service:3306/userdb

            - name: SPRING_DATASOURCE_USERNAME

              value: root

            - name: SPRING_DATASOURCE_PASSWORD

              value: root

---

apiVersion: v1

kind: Service

metadata:

  name: attendance-backend-service

spec:

  selector:

    app: attendance-backend

  ports:

    - protocol: TCP

      port: 8080

      targetPort: 8080

  type: ClusterIP