server {

    listen 80;

    # =========================
    # FRONTEND
    # =========================

    location / {

        proxy_pass http://frontend:3000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # =========================
    # AI FACE REGISTRATION
    # =========================

    location /api/face/register {

        proxy_pass http://ai-service:5000/register-face;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # =========================
    # AI FACE RECOGNITION
    # =========================

    location /api/face/recognize {

        proxy_pass http://ai-service:5000/recognize-face;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # =========================
    # SPRING BOOT APIs
    # =========================

    location /api/ {

        proxy_pass http://backend:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}